## 1. Lectura y verificación estructural
**Enunciado:** Importar fincas_produccion_cafe.csv en df_fincas sin generar columnas de índice duplicadas.

In [25]:
import pandas as pd

In [26]:
# Leer el archivo CSV sin usar ninguna columna como índice
df_fincas = pd.read_csv("fincas_produccion_cafe.csv", index_col=False)
df_fincas.head()

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
2,FIN-8003,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade

In [27]:
# Dimensiones (filas, columnas)
df_fincas.shape

(1012, 8)

In [28]:
# Tipos de dato y valores no nulos
df_fincas.info()

<class 'pandas.DataFrame'>
RangeIndex: 1012 entries, 0 to 1011
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID_Finca            1012 non-null   str
 1   Municipio           1012 non-null   str
 2   Variedad            1012 non-null   str
 3   Metodo_Beneficio    1012 non-null   str
 4   Area_Hectareas      957 non-null    float64
 5   Kilos_Recolectados  972 non-null    float64
 6   Altitud_MSNM        1012 non-null   int64
 7   Certificacion       1012 non-null   str
dtypes: float64(2), int64(1), str(5)
memory usage: 63.4 KB

## 2. Selección unidimensional y proyección multivariable
**Enunciado:** Extraer Variedad como Serie y, en otra instrucción, una tabla con Municipio, Area_Hectareas y Kilos_Recolectados.

In [29]:
# Seleccionar una columna (Serie)
variedad = df_fincas["Variedad"]
variedad.head(), type(variedad)

(0    Cenicafé 1
 1    Cenicafé 1
 2    Cenicafé 1
 3    Cenicafé 1
 4      Castillo
 Name: Variedad, dtype: str,
 pandas.Series)

In [30]:
# Seleccionar varias columnas (DataFrame)
df_fincas[["Municipio", "Area_Hectareas", "Kilos_Recolectados"]]

      Municipio  Area_Hectareas  Kilos_Recolectados
0     Chinchiná             3.0              4800.0
1     Manizales             5.5              2500.0
2     Manizales             1.5              1200.0
3     Risaralda             3.0              4800.0
4     Chinchiná             8.0             16000.0
...         ...             ...                 ...
1007  Manizales             5.5              2500.0
1008  Manizales            12.0              7500.0
1009  Palestina             5.5              4800.0
1010  Risaralda            12.0                 NaN
1011    Anserma             1.5              2500.0

[1012 rows x 3 columns]

## 3. Acceso por etiqueta (loc)
**Enunciado:** Consultar todos los datos del predio en el índice 280 con .loc[].

In [31]:
# Filtrar por índice
fila = df_fincas.loc[280]
fila

ID_Finca               FIN-8281
Municipio             Risaralda
Variedad               Colombia
Metodo_Beneficio        Natural
Area_Hectareas              5.5
Kilos_Recolectados      16000.0
Altitud_MSNM               1821
Certificacion          Orgánico
Name: 280, dtype: object

## 4. Eliminación de filas duplicadas
**Enunciado:** Aplicar .drop_duplicates() para dejar una base limpia.

In [32]:
# Contar las filas duplicadas
df_fincas.duplicated().sum()

np.int64(12)

In [33]:
# Eliminar duplicados
df_fincas = df_fincas.drop_duplicates()
df_fincas.shape

(1000, 8)

## 5. Filtrado condicional básico
**Enunciado:** Identificar los lotes con Altitud_MSNM > 1750.

In [34]:
# Filtrar por condiciones
df_fincas[df_fincas["Altitud_MSNM"] > 1750]

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
2,FIN-8003,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade
12,FIN-8013,Risaralda,Borbon Rosado,Natural,5.5,4800.0,1993,Rainforest Alliance
13,FIN-8014,Manizales,Borbon Rosado,Natural,1.5,2500.0,2011,Fairtrade
...,...,...,...,...,...,...,...,...
980,FIN-8981,Palestina,Castillo,Natural,12.0,7500.0,1968,Fairtrade
981,FIN-8982,Risaralda,Colombia,Honey,8.0,4800.0,2020,Fairtrade
984,FIN-8985,Chinchiná,Geisha,Lavado Tradicional,12.0,1200.0,1780,Fairtrade
985,FIN-8986,Anserma,Borbon Rosado,Lavado Tradicional,8.0,4800.0,1874,Fairtrade
995,FIN-8996,Anserma,Geisha,Natural,3.0,7500.0,1774,Rainforest Alliance

## 6. Filtrado categórico por lista (isin)
**Enunciado:** Seleccionar los predios de los municipios Anserma y Risaralda.

In [35]:
# Filtrar por lista de valores (isin)
df_fincas[df_fincas["Municipio"].isin(["Anserma", "Risaralda"])]

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
5,FIN-8006,Risaralda,Cenicafé 1,Honey,12.0,7500.0,1652,Orgánico
6,FIN-8007,Anserma,Colombia,Honey,5.5,4800.0,1674,Rainforest Alliance
10,FIN-8011,Risaralda,Cenicafé 1,Lavado Tradicional,5.5,2500.0,1710,Orgánico
11,FIN-8012,Anserma,Geisha,Natural,12.0,16000.0,1743,Ninguna
...,...,...,...,...,...,...,...,...
988,FIN-8989,Anserma,Geisha,Natural,1.5,7500.0,1513,Fairtrade
991,FIN-8992,Anserma,Cenicafé 1,Lavado Tradicional,3.0,1200.0,1347,Fairtrade
993,FIN-8994,Anserma,Castillo,Honey,1.5,4800.0,1702,Rainforest Alliance
995,FIN-8996,Anserma,Geisha,Natural,3.0,7500.0,1774,Rainforest Alliance
997,FIN-8998,Anserma,Colombia,Natural,NaN,1200.0,1395,Rainforest Alliance

## 7. Filtrado por intervalo numérico (between)
**Enunciado:** Aislar los lotes con Area_Hectareas entre 3.0 y 8.0 inclusive.

In [36]:
# Filtrar por área entre 3.0 y 8.0 hectáreas (inclusive)
df_fincas[df_fincas["Area_Hectareas"].between(3.0, 8.0)]

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade
6,FIN-8007,Anserma,Colombia,Honey,5.5,4800.0,1674,Rainforest Alliance
...,...,...,...,...,...,...,...,...
992,FIN-8993,Chinchiná,Castillo,Natural,3.0,2500.0,1508,Ninguna
994,FIN-8995,Chinchiná,Cenicafé 1,Natural,5.5,1200.0,1297,Fairtrade
995,FIN-8996,Anserma,Geisha,Natural,3.0,7500.0,1774,Rainforest Alliance
996,FIN-8997,Palestina,Borbon Rosado,Natural,3.0,4800.0,1263,Rainforest Alliance
998,FIN-8999,Manizales,Cenicafé 1,Lavado Tradicional,8.0,4800.0,1283,Fairtrade

## 8. Consultas directas con .query()
**Enunciado:** Extraer fincas con Certificacion == 'Orgánico' y Kilos_Recolectados > 5000.

In [37]:
# Filtrar por una query
df_fincas.query("Certificacion == 'Orgánico' and Kilos_Recolectados > 5000")

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
5,FIN-8006,Risaralda,Cenicafé 1,Honey,12.0,7500.0,1652,Orgánico
30,FIN-8031,Palestina,Castillo,Natural,18.5,16000.0,1838,Orgánico
34,FIN-8035,Chinchiná,Borbon Rosado,Natural,3.0,7500.0,1578,Orgánico
61,FIN-8062,Palestina,Geisha,Lavado Tradicional,1.5,11000.0,1885,Orgánico
69,FIN-8070,Palestina,Castillo,Lavado Tradicional,8.0,16000.0,1922,Orgánico
111,FIN-8112,Risaralda,Castillo,Honey,NaN,7500.0,1641,Orgánico
173,FIN-8174,Palestina,Colombia,Lavado Tradicional,NaN,7500.0,2018,Orgánico
187,FIN-8188,Manizales,Geisha,Lavado Tradicional,5.5,7500.0,1328,Orgánico
200,FIN-8201,Risaralda,Colombia,Honey,3.0,7500.0,1563,Orgánico
209,FIN-8210,Palestina,Geisha,Natural,5.5,7500.0,1540,Orgánico
235,FIN-8236,Risaralda,Castillo,Honey,NaN,7500.0,1437,Orgánico
280,FIN-8281,Risaralda,Colombia,Natural,5.5,16000.0,1821,Orgánico
287,FIN-8288,Risaralda,Cenicafé 1,Honey,NaN,7500.0,1648,Orgánico
325,FIN-8326,Palestina,Castillo,Lavado Tradicional,8.0,11000.0,1777,Orgánico
376,FIN-8377,Manizales,Castillo,Lavado Tradicional,5.5,11000.0,1508,Orgánico
397,FIN-8398,Manizales,Colombia,Honey,5.5,11000.0,1525,Orgánico
438,FIN-8439,Manizales,Colombia,Honey,1.5,7500.0,1324,Orgánico
443,FIN-8444,Chinchiná,Castillo,Lavado Tradicional,12.0,7500.0,1596,Orgánico
504,FIN-8505,Palestina,Geisha,Natural,18.5,7500.0,1528,Orgánico
522,FIN-8523,Risaralda,Borbon Rosado,Natural,3.0,11000.0,1551,Orgánico
552,FIN-8553,Risaralda,Colombia,Lavado Tradicional,12.0,11000.0,1579,Orgánico
553,FIN-8554,Palestina,Castillo,Lavado Tradicional,5.5,7500.0,1621,Orgánico
589,FIN-8590,Anserma,Geisha,Honey,12.0,7500.0,2033,Orgánico
603,FIN-8604,Chinchiná,Castillo,Natural,1.5,7500.0,1819,Orgánico
612,FIN-8613,Risaralda,Castillo,Honey,8.0,7500.0,1969,Orgánico
639,FIN-8640,Risaralda,Geisha,Lavado Tradicional,3.0,11000.0,1398,Orgánico
657,FIN-8658,Anserma,Colombia,Natural,5.5,7500.0,1931,Orgánico
659,FIN-8660,Manizales,Colombia,Honey,8.0,7500.0,1407,Orgánico
691,FIN-8692,Risaralda,Colombia,Natural,3.0,16000.0,1950,Orgánico
701,FIN-8702,Manizales,Geisha,Honey,5.5,7500.0,1325,Orgánico
720,FIN-8721,Anserma,Borbon Rosado,Honey,1.5,7500.0,1356,Orgánico
738,FIN-8739,Anserma,Borbon Rosado,Natural,1.5,16000.0,1934,Orgánico
815,FIN-8816,Risaralda,Colombia,Lavado Tradicional,3.0,16000.0,1569,Orgánico
821,FIN-8822,Anserma,Geisha,Honey,3.0,16000.0,2023,Orgánico
877,FIN-8878,Palestina,Cenicafé 1,Honey,1.5,16000.0,1501,Orgánico
900,FIN-8901,Chinchiná,Geisha,Honey,1.5,11000.0,1433,Orgánico
904,FIN-8905,Anserma,Colombia,Lavado Tradicional,3.0,7500.0,1523,Orgánico
913,FIN-8914,Risaralda,Colombia,Honey,3.0,7500.0,1548,Orgánico
942,FIN-8943,Chinchiná,Borbon Rosado,Lavado Tradicional,8.0,11000.0,1660,Orgánico
982,FIN-8983,Anserma,Borbon Rosado,Honey,8.0,11000.0,1684,Orgánico

## 9. Filtrado compuesto con métodos de texto
**Enunciado:** Fincas cuyo Metodo_Beneficio inicie con 'Lavado' y cuya Variedad sea 'Geisha'.

In [38]:
# Filtrar por condiciones y conectores
lavado = df_fincas["Metodo_Beneficio"].str.startswith("Lavado")
geisha = df_fincas["Variedad"] == "Geisha"

filtro = lavado & geisha
df_fincas[filtro]

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion
16,FIN-8017,Palestina,Geisha,Lavado Tradicional,3.0,4800.0,1837,Rainforest Alliance
18,FIN-8019,Manizales,Geisha,Lavado Tradicional,12.0,7500.0,1500,Fairtrade
38,FIN-8039,Anserma,Geisha,Lavado Tradicional,18.5,1200.0,1675,Rainforest Alliance
50,FIN-8051,Chinchiná,Geisha,Lavado Tradicional,3.0,7500.0,1689,Rainforest Alliance
61,FIN-8062,Palestina,Geisha,Lavado Tradicional,1.5,11000.0,1885,Orgánico
...,...,...,...,...,...,...,...,...
943,FIN-8944,Manizales,Geisha,Lavado Tradicional,5.5,NaN,1313,Rainforest Alliance
946,FIN-8947,Chinchiná,Geisha,Lavado Tradicional,NaN,11000.0,1615,Ninguna
953,FIN-8954,Risaralda,Geisha,Lavado Tradicional,1.5,11000.0,1812,Rainforest Alliance
984,FIN-8985,Chinchiná,Geisha,Lavado Tradicional,12.0,1200.0,1780,Fairtrade
987,FIN-8988,Anserma,Geisha,Lavado Tradicional,8.0,2500.0,1654,Fairtrade

## 10. Imputación de valores faltantes
**Enunciado:** Reemplazar NaN de Area_Hectareas por su promedio y los de Kilos_Recolectados por 0.0 con .fillna().

In [39]:
# Contar valores nulos por columna
df_fincas.isna().sum()

ID_Finca               0
Municipio              0
Variedad               0
Metodo_Beneficio       0
Area_Hectareas        55
Kilos_Recolectados    39
Altitud_MSNM           0
Certificacion          0
dtype: int64

In [40]:
# Rellenar valores faltantes
df_fincas = df_fincas.fillna(
    {
        "Area_Hectareas": df_fincas["Area_Hectareas"].mean(),
        "Kilos_Recolectados": 0.0
    }
)
df_fincas.isna().sum()

ID_Finca              0
Municipio             0
Variedad              0
Metodo_Beneficio      0
Area_Hectareas        0
Kilos_Recolectados    0
Altitud_MSNM          0
Certificacion         0
dtype: int64

## 11. Transformación y creación de columnas con .apply()
**Enunciado:** Crear una función de rendimiento por hectárea y aplicarla para crear Rendimiento_Kilos_Ha.

In [41]:
# Transformación de datos
def rendimiento(fila):
    return fila["Kilos_Recolectados"] / fila["Area_Hectareas"]

df_fincas["Rendimiento_Kilos_Ha"] = df_fincas.apply(rendimiento, axis=1)
df_fincas.head()

,ID_Finca,Municipio,Variedad,Metodo_Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud_MSNM,Certificacion,Rendimiento_Kilos_Ha
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna,1600.000000
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance,454.545455
2,FIN-8003,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance,800.000000
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna,1600.000000
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade,2000.000000

## 12. Renombrado y reordenamiento de atributos
**Enunciado:** Renombrar Metodo_Beneficio → Beneficio y Altitud_MSNM → Altitud; poner ID_Finca y Rendimiento_Kilos_Ha al inicio.

In [42]:
# Renombrar columnas
df_fincas = df_fincas.rename(
    columns = {
        "Metodo_Beneficio": "Beneficio",
        "Altitud_MSNM": "Altitud"
    }
)
df_fincas.head()

,ID_Finca,Municipio,Variedad,Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud,Certificacion,Rendimiento_Kilos_Ha
0,FIN-8001,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna,1600.000000
1,FIN-8002,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance,454.545455
2,FIN-8003,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance,800.000000
3,FIN-8004,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna,1600.000000
4,FIN-8005,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade,2000.000000

In [43]:
# Reordenar columnas
columnas_ordenadas = [
    "ID_Finca", "Rendimiento_Kilos_Ha", "Municipio", "Variedad", "Beneficio",
    "Area_Hectareas", "Kilos_Recolectados", "Altitud", "Certificacion"
]
df_fincas = df_fincas[columnas_ordenadas]
df_fincas.head()

,ID_Finca,Rendimiento_Kilos_Ha,Municipio,Variedad,Beneficio,Area_Hectareas,Kilos_Recolectados,Altitud,Certificacion
0,FIN-8001,1600.000000,Chinchiná,Cenicafé 1,Honey,3.0,4800.0,1500,Ninguna
1,FIN-8002,454.545455,Manizales,Cenicafé 1,Natural,5.5,2500.0,1284,Rainforest Alliance
2,FIN-8003,800.000000,Manizales,Cenicafé 1,Lavado Tradicional,1.5,1200.0,1959,Rainforest Alliance
3,FIN-8004,1600.000000,Risaralda,Cenicafé 1,Lavado Tradicional,3.0,4800.0,1767,Ninguna
4,FIN-8005,2000.000000,Chinchiná,Castillo,Natural,8.0,16000.0,1929,Fairtrade

## 13. Agrupación y métricas de producción por municipio
**Enunciado:** Agrupar por Municipio y calcular promedio de Altitud y suma de Kilos_Recolectados con .agg().

In [44]:
# Agrupar los datos por municipio
grouped = df_fincas.groupby("Municipio")

# Promedio de altitud y suma de kilos por municipio
aggregated_data = grouped.agg(
    {
        "Altitud": "mean",
        "Kilos_Recolectados": "sum"
    }
)
aggregated_data

               Altitud  Kilos_Recolectados
Municipio
Anserma    1637.025773            882900.0
Chinchiná  1625.582011            916700.0
Manizales  1637.788177            959600.0
Palestina  1638.493213           1111500.0
Risaralda  1647.020725            978700.0

## 14. Dispersión con función personalizada
**Enunciado:** Crear rango(series) = max - min y aplicarla con .agg() sobre Area_Hectareas y Kilos_Recolectados agrupando por Variedad.

In [45]:
# Definir una función de agregación personalizada
def rango(series):
    return series.max() - series.min()

# Agrupar por variedad y aplicar la función
grouped_variedad = df_fincas.groupby("Variedad")
aggregated_data_custom = grouped_variedad.agg(
    {
        "Area_Hectareas": rango,
        "Kilos_Recolectados": rango
    }
)
aggregated_data_custom

               Area_Hectareas  Kilos_Recolectados
Variedad
Borbon Rosado            17.0             16000.0
Castillo                 17.0             16000.0
Cenicafé 1               17.0             16000.0
Colombia                 17.0             16000.0
Geisha                   17.0             16000.0

## 15. Agrupamiento multinivel
**Enunciado:** Agrupar por Municipio y Variedad, con promedio de Altitud y suma de Kilos_Recolectados.

In [46]:
# Agrupar por municipio y variedad
grouped_multi = df_fincas.groupby(["Municipio", "Variedad"])

# Promedio de altitud y suma de kilos por cada combinación
aggregated_multi = grouped_multi.agg(
    {
        "Altitud": "mean",
        "Kilos_Recolectados": "sum"
    }
)
aggregated_multi

                             Altitud  Kilos_Recolectados
Municipio Variedad
Anserma   Borbon Rosado  1664.538462            177100.0
          Castillo       1587.000000            215300.0
          Cenicafé 1     1599.600000             85300.0
          Colombia       1645.613636            191000.0
          Geisha         1677.166667            214200.0
Chinchiná Borbon Rosado  1620.673469            255100.0
          Castillo       1651.000000            237200.0
          Cenicafé 1     1567.882353            172400.0
          Colombia       1691.500000            115000.0
          Geisha         1606.857143            137000.0
Manizales Borbon Rosado  1703.341463            193800.0
          Castillo       1653.488889            215700.0
          Cenicafé 1     1616.000000            170700.0
          Colombia       1627.538462            200100.0
          Geisha         1581.000000            179300.0
Palestina Borbon Rosado  1629.276596            223800.0
          Castillo       1627.820000            265300.0
          Cenicafé 1     1650.300000            248300.0
          Colombia       1645.136364            215200.0
          Geisha         1641.300000            158900.0
Risaralda Borbon Rosado  1707.909091            138500.0
          Castillo       1686.868421            171900.0
          Cenicafé 1     1626.976744            239100.0
          Colombia       1612.736842            213800.0
          Geisha         1613.878049            215400.0